//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleValidator.AddressValidatorServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoogleService.languages", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    public enum GoogleServicelanguages : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ar = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        bg = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        bn = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ca = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cs = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        da = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        de = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        el = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        en = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        en_AU = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        en_GB = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        es = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        eu = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fa = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fi = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fil = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fr = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        gl = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        gu = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        hi = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        hr = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        hu = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        id = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        it = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        iw = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ja = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        kn = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ko = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        lt = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        lv = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ml = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        mr = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nl = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        no = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        pl = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        pt = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        pt_BR = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        pt_PT = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ro = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ru = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sk = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sl = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sr = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sv = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ta = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        te = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        th = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        tl = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        tr = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        uk = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        vi = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        zh_CN = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        zh_TW = 52,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeocodeResponse", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    [System.SerializableAttribute()]
    public partial class GeocodeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string error_messagek__BackingFieldField;
        
        private string xmlk__BackingFieldField;
        
        private GoogleValidator.AddressValidatorServiceProxy.result[] resultFieldField;
        
        private GoogleValidator.AddressValidatorServiceProxy.status statusFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<error_message>k__BackingField", IsRequired=true)]
        public string error_messagek__BackingField {
            get {
                return this.error_messagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.error_messagek__BackingFieldField, value) != true)) {
                    this.error_messagek__BackingFieldField = value;
                    this.RaisePropertyChanged("error_messagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<xml>k__BackingField", IsRequired=true)]
        public string xmlk__BackingField {
            get {
                return this.xmlk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.xmlk__BackingFieldField, value) != true)) {
                    this.xmlk__BackingFieldField = value;
                    this.RaisePropertyChanged("xmlk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GoogleValidator.AddressValidatorServiceProxy.result[] resultField {
            get {
                return this.resultFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.resultFieldField, value) != true)) {
                    this.resultFieldField = value;
                    this.RaisePropertyChanged("resultField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GoogleValidator.AddressValidatorServiceProxy.status statusField {
            get {
                return this.statusFieldField;
            }
            set {
                if ((this.statusFieldField.Equals(value) != true)) {
                    this.statusFieldField = value;
                    this.RaisePropertyChanged("statusField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="result", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    [System.SerializableAttribute()]
    public partial class result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GoogleValidator.AddressValidatorServiceProxy.address_component[] address_componentFieldField;
        
        private string formatted_addressFieldField;
        
        private GoogleValidator.AddressValidatorServiceProxy.geometry geometryFieldField;
        
        private bool partial_matchFieldField;
        
        private string place_idFieldField;
        
        private GoogleValidator.AddressValidatorServiceProxy.type typeFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GoogleValidator.AddressValidatorServiceProxy.address_component[] address_componentField {
            get {
                return this.address_componentFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.address_componentFieldField, value) != true)) {
                    this.address_componentFieldField = value;
                    this.RaisePropertyChanged("address_componentField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string formatted_addressField {
            get {
                return this.formatted_addressFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.formatted_addressFieldField, value) != true)) {
                    this.formatted_addressFieldField = value;
                    this.RaisePropertyChanged("formatted_addressField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GoogleValidator.AddressValidatorServiceProxy.geometry geometryField {
            get {
                return this.geometryFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.geometryFieldField, value) != true)) {
                    this.geometryFieldField = value;
                    this.RaisePropertyChanged("geometryField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool partial_matchField {
            get {
                return this.partial_matchFieldField;
            }
            set {
                if ((this.partial_matchFieldField.Equals(value) != true)) {
                    this.partial_matchFieldField = value;
                    this.RaisePropertyChanged("partial_matchField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string place_idField {
            get {
                return this.place_idFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.place_idFieldField, value) != true)) {
                    this.place_idFieldField = value;
                    this.RaisePropertyChanged("place_idField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GoogleValidator.AddressValidatorServiceProxy.type typeField {
            get {
                return this.typeFieldField;
            }
            set {
                if ((this.typeFieldField.Equals(value) != true)) {
                    this.typeFieldField = value;
                    this.RaisePropertyChanged("typeField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="status", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    public enum status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZERO_RESULTS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OVER_QUERY_LIMIT = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUEST_DENIED = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_REQUEST = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="geometry", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    [System.SerializableAttribute()]
    public partial class geometry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GoogleValidator.AddressValidatorServiceProxy.location locationFieldField;
        
        private GoogleValidator.AddressValidatorServiceProxy.location_type location_typeFieldField;
        
        private GoogleValidator.AddressValidatorServiceProxy.viewport viewportFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GoogleValidator.AddressValidatorServiceProxy.location locationField {
            get {
                return this.locationFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.locationFieldField, value) != true)) {
                    this.locationFieldField = value;
                    this.RaisePropertyChanged("locationField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GoogleValidator.AddressValidatorServiceProxy.location_type location_typeField {
            get {
                return this.location_typeFieldField;
            }
            set {
                if ((this.location_typeFieldField.Equals(value) != true)) {
                    this.location_typeFieldField = value;
                    this.RaisePropertyChanged("location_typeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GoogleValidator.AddressValidatorServiceProxy.viewport viewportField {
            get {
                return this.viewportFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.viewportFieldField, value) != true)) {
                    this.viewportFieldField = value;
                    this.RaisePropertyChanged("viewportField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="address_component", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    [System.SerializableAttribute()]
    public partial class address_component : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string long_nameFieldField;
        
        private string short_nameFieldField;
        
        private GoogleValidator.AddressValidatorServiceProxy.type[] typeFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string long_nameField {
            get {
                return this.long_nameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.long_nameFieldField, value) != true)) {
                    this.long_nameFieldField = value;
                    this.RaisePropertyChanged("long_nameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string short_nameField {
            get {
                return this.short_nameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.short_nameFieldField, value) != true)) {
                    this.short_nameFieldField = value;
                    this.RaisePropertyChanged("short_nameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GoogleValidator.AddressValidatorServiceProxy.type[] typeField {
            get {
                return this.typeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.typeFieldField, value) != true)) {
                    this.typeFieldField = value;
                    this.RaisePropertyChanged("typeField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="type", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    public enum type : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        street_address = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        route = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        intersection = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        political = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        country = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        administrative_area_level_1 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        administrative_area_level_2 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        administrative_area_level_3 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        administrative_area_level_4 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        administrative_area_level_5 = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sublocality_level_1 = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sublocality_level_2 = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sublocality_level_3 = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sublocality_level_4 = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sublocality_level_5 = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        colloquial_area = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        locality = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sublocality = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        neighborhood = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        premise = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        subpremise = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        postal_code = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        natural_feature = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        airport = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        park = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        point_of_interest = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        post_box = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        street_number = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        floor = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        room = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        establishment = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        postal_town = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        postal_code_prefix = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        bus_station = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        subway_station = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        transit_station = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        museum = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        place_of_worship = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        university = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        train_station = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        campground = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        lodging = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        post_office = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fire_station = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        church = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        pharmacy = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        doctor = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        school = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        parking = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        amusement_park = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cemetery = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        hospital = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        library = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        police = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        zoo = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        store = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        stadium = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        health = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        courthouse = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        city_hall = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        finance = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        dentist = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        embassy = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        aquarium = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        local_government_office = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        food = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        storage = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        real_estate_agency = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        general_contractor = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ward = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        postal_code_suffix = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cafe = 71,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="location", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    [System.SerializableAttribute()]
    public partial class location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal latFieldField;
        
        private decimal lngFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal latField {
            get {
                return this.latFieldField;
            }
            set {
                if ((this.latFieldField.Equals(value) != true)) {
                    this.latFieldField = value;
                    this.RaisePropertyChanged("latField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal lngField {
            get {
                return this.lngFieldField;
            }
            set {
                if ((this.lngFieldField.Equals(value) != true)) {
                    this.lngFieldField = value;
                    this.RaisePropertyChanged("lngField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="viewport", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    [System.SerializableAttribute()]
    public partial class viewport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GoogleValidator.AddressValidatorServiceProxy.northeast northeastFieldField;
        
        private GoogleValidator.AddressValidatorServiceProxy.southwest southwestFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GoogleValidator.AddressValidatorServiceProxy.northeast northeastField {
            get {
                return this.northeastFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.northeastFieldField, value) != true)) {
                    this.northeastFieldField = value;
                    this.RaisePropertyChanged("northeastField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GoogleValidator.AddressValidatorServiceProxy.southwest southwestField {
            get {
                return this.southwestFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.southwestFieldField, value) != true)) {
                    this.southwestFieldField = value;
                    this.RaisePropertyChanged("southwestField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="location_type", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    public enum location_type : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROOFTOP = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RANGE_INTERPOLATED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GEOMETRIC_CENTER = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        APPROXIMATE = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="northeast", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    [System.SerializableAttribute()]
    public partial class northeast : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal latFieldField;
        
        private decimal lngFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal latField {
            get {
                return this.latFieldField;
            }
            set {
                if ((this.latFieldField.Equals(value) != true)) {
                    this.latFieldField = value;
                    this.RaisePropertyChanged("latField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal lngField {
            get {
                return this.lngFieldField;
            }
            set {
                if ((this.lngFieldField.Equals(value) != true)) {
                    this.lngFieldField = value;
                    this.RaisePropertyChanged("lngField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="southwest", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    [System.SerializableAttribute()]
    public partial class southwest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal latFieldField;
        
        private decimal lngFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal latField {
            get {
                return this.latFieldField;
            }
            set {
                if ((this.latFieldField.Equals(value) != true)) {
                    this.latFieldField = value;
                    this.RaisePropertyChanged("latField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal lngField {
            get {
                return this.lngFieldField;
            }
            set {
                if ((this.lngFieldField.Equals(value) != true)) {
                    this.lngFieldField = value;
                    this.RaisePropertyChanged("lngField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeoCoordinates", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    [System.SerializableAttribute()]
    public partial class GeoCoordinates : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GoogleValidator.AddressValidatorServiceProxy.location_type LocationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GoogleValidator.AddressValidatorServiceProxy.location_type LocationType {
            get {
                return this.LocationTypeField;
            }
            set {
                if ((this.LocationTypeField.Equals(value) != true)) {
                    this.LocationTypeField = value;
                    this.RaisePropertyChanged("LocationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/AddressValidator")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormattedAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GoogleValidator.AddressValidatorServiceProxy.location_type LocationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PartialMatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PremiseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormattedAddress {
            get {
                return this.FormattedAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FormattedAddressField, value) != true)) {
                    this.FormattedAddressField = value;
                    this.RaisePropertyChanged("FormattedAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullAddress {
            get {
                return this.FullAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FullAddressField, value) != true)) {
                    this.FullAddressField = value;
                    this.RaisePropertyChanged("FullAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string House {
            get {
                return this.HouseField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseField, value) != true)) {
                    this.HouseField = value;
                    this.RaisePropertyChanged("House");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GoogleValidator.AddressValidatorServiceProxy.location_type LocationType {
            get {
                return this.LocationTypeField;
            }
            set {
                if ((this.LocationTypeField.Equals(value) != true)) {
                    this.LocationTypeField = value;
                    this.RaisePropertyChanged("LocationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PartialMatch {
            get {
                return this.PartialMatchField;
            }
            set {
                if ((this.PartialMatchField.Equals(value) != true)) {
                    this.PartialMatchField = value;
                    this.RaisePropertyChanged("PartialMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Premise {
            get {
                return this.PremiseField;
            }
            set {
                if ((object.ReferenceEquals(this.PremiseField, value) != true)) {
                    this.PremiseField = value;
                    this.RaisePropertyChanged("Premise");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateCode {
            get {
                return this.StateCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StateCodeField, value) != true)) {
                    this.StateCodeField = value;
                    this.RaisePropertyChanged("StateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddressValidatorServiceProxy.IAddressValidatorService")]
    public interface IAddressValidatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAddressText", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAddressTextResponse")]
        GoogleValidator.AddressValidatorServiceProxy.GeocodeResponse ValidateAddressText(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAddressText", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAddressTextResponse")]
        System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.GeocodeResponse> ValidateAddressTextAsync(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAddressParts", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAddressPartsResponse")]
        GoogleValidator.AddressValidatorServiceProxy.GeocodeResponse ValidateAddressParts(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAddressParts", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAddressPartsResponse")]
        System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.GeocodeResponse> ValidateAddressPartsAsync(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAddressTextSuggestions", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAddressTextSuggestionsRespons" +
            "e")]
        string[] ValidateAddressTextSuggestions(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAddressTextSuggestions", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAddressTextSuggestionsRespons" +
            "e")]
        System.Threading.Tasks.Task<string[]> ValidateAddressTextSuggestionsAsync(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAddressPartsSuggestions", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAddressPartsSuggestionsRespon" +
            "se")]
        string[] ValidateAddressPartsSuggestions(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAddressPartsSuggestions", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAddressPartsSuggestionsRespon" +
            "se")]
        System.Threading.Tasks.Task<string[]> ValidateAddressPartsSuggestionsAsync(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/GetCoordinatesOfAddressText", ReplyAction="http://tempuri.org/IAddressValidatorService/GetCoordinatesOfAddressTextResponse")]
        GoogleValidator.AddressValidatorServiceProxy.GeoCoordinates GetCoordinatesOfAddressText(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/GetCoordinatesOfAddressText", ReplyAction="http://tempuri.org/IAddressValidatorService/GetCoordinatesOfAddressTextResponse")]
        System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.GeoCoordinates> GetCoordinatesOfAddressTextAsync(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/GetCoordinatesOfAddressSuggestions", ReplyAction="http://tempuri.org/IAddressValidatorService/GetCoordinatesOfAddressSuggestionsRes" +
            "ponse")]
        GoogleValidator.AddressValidatorServiceProxy.GeoCoordinates[] GetCoordinatesOfAddressSuggestions(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/GetCoordinatesOfAddressSuggestions", ReplyAction="http://tempuri.org/IAddressValidatorService/GetCoordinatesOfAddressSuggestionsRes" +
            "ponse")]
        System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.GeoCoordinates[]> GetCoordinatesOfAddressSuggestionsAsync(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressText", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressTextResponse")]
        GoogleValidator.AddressValidatorServiceProxy.Address ValidateAndGetAddressText(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressText", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressTextResponse")]
        System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.Address> ValidateAndGetAddressTextAsync(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressSuggeestions", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressSuggeestionsResp" +
            "onse")]
        GoogleValidator.AddressValidatorServiceProxy.Address[] ValidateAndGetAddressSuggeestions(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressSuggeestions", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressSuggeestionsResp" +
            "onse")]
        System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.Address[]> ValidateAndGetAddressSuggeestionsAsync(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressParts", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressPartsResponse")]
        GoogleValidator.AddressValidatorServiceProxy.Address ValidateAndGetAddressParts(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressParts", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressPartsResponse")]
        System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.Address> ValidateAndGetAddressPartsAsync(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressPartsSuggestions" +
            "", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressPartsSuggestions" +
            "Response")]
        GoogleValidator.AddressValidatorServiceProxy.Address[] ValidateAndGetAddressPartsSuggestions(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressPartsSuggestions" +
            "", ReplyAction="http://tempuri.org/IAddressValidatorService/ValidateAndGetAddressPartsSuggestions" +
            "Response")]
        System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.Address[]> ValidateAndGetAddressPartsSuggestionsAsync(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/GetAddressSuggestionsByCoordinates", ReplyAction="http://tempuri.org/IAddressValidatorService/GetAddressSuggestionsByCoordinatesRes" +
            "ponse")]
        string[] GetAddressSuggestionsByCoordinates(decimal latitude, decimal longitude, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/GetAddressSuggestionsByCoordinates", ReplyAction="http://tempuri.org/IAddressValidatorService/GetAddressSuggestionsByCoordinatesRes" +
            "ponse")]
        System.Threading.Tasks.Task<string[]> GetAddressSuggestionsByCoordinatesAsync(decimal latitude, decimal longitude, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/GetAddressPartsSuggestionsByCoordinat" +
            "es", ReplyAction="http://tempuri.org/IAddressValidatorService/GetAddressPartsSuggestionsByCoordinat" +
            "esResponse")]
        GoogleValidator.AddressValidatorServiceProxy.Address[] GetAddressPartsSuggestionsByCoordinates(decimal latitude, decimal longitude, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/GetAddressPartsSuggestionsByCoordinat" +
            "es", ReplyAction="http://tempuri.org/IAddressValidatorService/GetAddressPartsSuggestionsByCoordinat" +
            "esResponse")]
        System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.Address[]> GetAddressPartsSuggestionsByCoordinatesAsync(decimal latitude, decimal longitude, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/GetAddressByCoordinates", ReplyAction="http://tempuri.org/IAddressValidatorService/GetAddressByCoordinatesResponse")]
        GoogleValidator.AddressValidatorServiceProxy.GeocodeResponse GetAddressByCoordinates(decimal latitude, decimal longitude, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressValidatorService/GetAddressByCoordinates", ReplyAction="http://tempuri.org/IAddressValidatorService/GetAddressByCoordinatesResponse")]
        System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.GeocodeResponse> GetAddressByCoordinatesAsync(decimal latitude, decimal longitude, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddressValidatorServiceChannel : GoogleValidator.AddressValidatorServiceProxy.IAddressValidatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressValidatorServiceClient : System.ServiceModel.ClientBase<GoogleValidator.AddressValidatorServiceProxy.IAddressValidatorService>, GoogleValidator.AddressValidatorServiceProxy.IAddressValidatorService {
        
        public AddressValidatorServiceClient() {
        }
        
        public AddressValidatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressValidatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressValidatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressValidatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GoogleValidator.AddressValidatorServiceProxy.GeocodeResponse ValidateAddressText(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAddressText(address, language);
        }
        
        public System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.GeocodeResponse> ValidateAddressTextAsync(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAddressTextAsync(address, language);
        }
        
        public GoogleValidator.AddressValidatorServiceProxy.GeocodeResponse ValidateAddressParts(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAddressParts(country, state, postcode, city, street, house, language);
        }
        
        public System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.GeocodeResponse> ValidateAddressPartsAsync(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAddressPartsAsync(country, state, postcode, city, street, house, language);
        }
        
        public string[] ValidateAddressTextSuggestions(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAddressTextSuggestions(address, language);
        }
        
        public System.Threading.Tasks.Task<string[]> ValidateAddressTextSuggestionsAsync(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAddressTextSuggestionsAsync(address, language);
        }
        
        public string[] ValidateAddressPartsSuggestions(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAddressPartsSuggestions(country, state, postcode, city, street, house, language);
        }
        
        public System.Threading.Tasks.Task<string[]> ValidateAddressPartsSuggestionsAsync(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAddressPartsSuggestionsAsync(country, state, postcode, city, street, house, language);
        }
        
        public GoogleValidator.AddressValidatorServiceProxy.GeoCoordinates GetCoordinatesOfAddressText(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.GetCoordinatesOfAddressText(address, language);
        }
        
        public System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.GeoCoordinates> GetCoordinatesOfAddressTextAsync(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.GetCoordinatesOfAddressTextAsync(address, language);
        }
        
        public GoogleValidator.AddressValidatorServiceProxy.GeoCoordinates[] GetCoordinatesOfAddressSuggestions(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.GetCoordinatesOfAddressSuggestions(address, language);
        }
        
        public System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.GeoCoordinates[]> GetCoordinatesOfAddressSuggestionsAsync(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.GetCoordinatesOfAddressSuggestionsAsync(address, language);
        }
        
        public GoogleValidator.AddressValidatorServiceProxy.Address ValidateAndGetAddressText(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAndGetAddressText(address, language);
        }
        
        public System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.Address> ValidateAndGetAddressTextAsync(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAndGetAddressTextAsync(address, language);
        }
        
        public GoogleValidator.AddressValidatorServiceProxy.Address[] ValidateAndGetAddressSuggeestions(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAndGetAddressSuggeestions(address, language);
        }
        
        public System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.Address[]> ValidateAndGetAddressSuggeestionsAsync(string address, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAndGetAddressSuggeestionsAsync(address, language);
        }
        
        public GoogleValidator.AddressValidatorServiceProxy.Address ValidateAndGetAddressParts(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAndGetAddressParts(country, state, postcode, city, street, house, language);
        }
        
        public System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.Address> ValidateAndGetAddressPartsAsync(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAndGetAddressPartsAsync(country, state, postcode, city, street, house, language);
        }
        
        public GoogleValidator.AddressValidatorServiceProxy.Address[] ValidateAndGetAddressPartsSuggestions(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAndGetAddressPartsSuggestions(country, state, postcode, city, street, house, language);
        }
        
        public System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.Address[]> ValidateAndGetAddressPartsSuggestionsAsync(string country, string state, string postcode, string city, string street, string house, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.ValidateAndGetAddressPartsSuggestionsAsync(country, state, postcode, city, street, house, language);
        }
        
        public string[] GetAddressSuggestionsByCoordinates(decimal latitude, decimal longitude, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.GetAddressSuggestionsByCoordinates(latitude, longitude, language);
        }
        
        public System.Threading.Tasks.Task<string[]> GetAddressSuggestionsByCoordinatesAsync(decimal latitude, decimal longitude, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.GetAddressSuggestionsByCoordinatesAsync(latitude, longitude, language);
        }
        
        public GoogleValidator.AddressValidatorServiceProxy.Address[] GetAddressPartsSuggestionsByCoordinates(decimal latitude, decimal longitude, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.GetAddressPartsSuggestionsByCoordinates(latitude, longitude, language);
        }
        
        public System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.Address[]> GetAddressPartsSuggestionsByCoordinatesAsync(decimal latitude, decimal longitude, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.GetAddressPartsSuggestionsByCoordinatesAsync(latitude, longitude, language);
        }
        
        public GoogleValidator.AddressValidatorServiceProxy.GeocodeResponse GetAddressByCoordinates(decimal latitude, decimal longitude, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.GetAddressByCoordinates(latitude, longitude, language);
        }
        
        public System.Threading.Tasks.Task<GoogleValidator.AddressValidatorServiceProxy.GeocodeResponse> GetAddressByCoordinatesAsync(decimal latitude, decimal longitude, GoogleValidator.AddressValidatorServiceProxy.GoogleServicelanguages language) {
            return base.Channel.GetAddressByCoordinatesAsync(latitude, longitude, language);
        }
    }
}
